package edu.khai.voloshyn.travelagency.command.constants;

public enum CommandType {
    SIGN_UP, SIGN_IN, HOME, SIGN_OUT, GET_USERS_LIST, BLOCK_CLIENT,
    UNBLOCK_CLIENT, CREATE_ADMIN, UPDATE_ADMIN, CREATE_MANAGER, UPDATE_MANAGER, UPDATE_CLIENT, DELETE_CLIENT,
    GET_TOURS_LIST, GET_HOT_TOURS, SET_HOT_TOUR, UN_HOT_TOUR, DELETE_TOUR,
    GET_BY_CITY, GET_BY_HOTEL, GET_BY_TOURIST, GET_BY_TOUR_TYPE, ADD_TOUR, UPDATE_TOUR, REDIRECT_TO_UPDATE_TOUR_PAGE,
    REDIRECT_TO_INPUT_TOUR_NUMBER_PAGE, BUY_TOUR, CANCEL_BUYING_TOUR, SET_BOUGHT_ORDER,
    REDIRECT_TO_SUBMIT_BUY_PAGE, GET_ORDERS, GET_ORDERS_BY_USER_ID,
    SEARCH_TOURS, DELETE_TOUR_TYPE, DELETE_CITY, ADD_CITY, DELETE_HOTEL, ADD_HOTEL, DELETE_TOURIST, ADD_TOURIST, ADD_TOUR_TYPE,
    REDIRECT
}
